version: '3'
services:
    mongo:
        image: 'mongo'
        container_name: 'pubtalk-mongo'
        volumes: 
           # - ./mongo/init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - ./mongo-volume:/data/db
        ports:
            - '27017:27017'
    client:
        #image: 'ppulwey/cloudbucket:docker-try'
        container_name: 'pubtalk-api'
        build: .
        ports:
            - '8080:8080'
        depends_on: 
            - mongo